services:
  php:
    build: .
    container_name: php82
    volumes:
      - ./:/app
    working_dir: /app
    env_file:
      - .env
    command: symfony serve --no-tls --port=8000 --allow-http --allow-all-ip
    # command: php -S 0.0.0.0:8000 -t public
    ports:
      - "8000:8000"
